title: "Adam Hartshorne"
description: "Personal portfolio to showcase my projects with a focus on growing technical skills in IT"
theme: jekyll-theme-cayman
url: "https://AdamHartshorne.github.io"
author: 
  name: "Adam Hartshorne"
  email: "AdamJHartshorne@gmail.com"
