title: "Adam Hartshorne"
description: "Showcasing my learning"
theme: jekyll-theme-cayman
url: "https://AdamHartshorne.github.io"
author: 
  name: "Adam Hartshorne"
  email: "AdamJHartshorne@gmail.com"
